### ISSUE TITLE
404 There isn't a GitHub Pages site here

### ISSUE THREAD

**Issue by ChengLuffy** [hujiaweibujidao/Gank#1]
when I click 2016-05-13: swift 中的#available检测接口是否可用，there is a 404 page

**Comment by hujiaweibujidao** [comment]
@ChengLuffy 你好，这是因为这篇被推荐的文章现在无法访问了，你在干货集中营首页点击这篇推荐文章也是一样的404，我的应用只是获取被推荐的文章的网址然后用浏览器打开而已，未做其他解析。

**Comment by ChengLuffy** [comment]
啊哈？好吧，做得超级漂亮，加油
